local WORLD = require "world.world"
local COMMON = require "libs.common"
local JESTER = require "Jester.jester"

function init(self)
	COMMON.input_acquire()
	gui.set_render_order(2)
end

function final(self)
	COMMON.input_release()
end

function update(self, dt)

end

function on_input(self,action_id,action,sender)
	if action_id == COMMON.HASHES.INPUT_TOUCH and action.pressed then
		JESTER.reload()
	end
end
