local COMMON = require "libs.common"

function init(self)
	self.lbl_cpu = gui.get_node("lbl_cpu")
	self.lbl_memory = gui.get_node("lbl_memory")
	gui.set_render_order(15)
end

function final(self)
	-- Add finalization code here
	-- Remove this function if not needed
end

function update(self, dt)
	gui.set_text(self.lbl_cpu, "Cpu:" .. string.format("%.2f", profiler.get_cpu_usage()))
	gui.set_text(self.lbl_memory, "Mem:" .. string.format("%.2f Mb", profiler.get_memory_usage()/1024/1024))
end